### ISSUE TITLE
Does not work on 1.6.4

### ISSUE THREAD

**Issue by Zilacon** [Superior-Development/CommandViewer#8]
So your release version said it "should" work for all mc versions. And since all of your previous versions on bukkit did not work i gave this one a try. And again this one did not work either.

2015-03-27 13:52:40 [SEVERE] Could not load 'plugins/CommandViewer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class com.superiornetworks.commandviewer.CommandViewer
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:194)
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugins(CraftServer.java:231)
	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141)
	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.superiornetworks.commandviewer.CommandViewer
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:539)
	at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:456)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:234)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:183)
	... 15 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.md_5.specialsource.RemapperProcessor.process(RemapperProcessor.java:83)
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:495)
	... 22 more

Is what i get when i start up the server. This is being used on a MCPC+ 1.6.4 server.

**Comment by TiTo-418** [comment]
This can be closed https://github.com/Superior-Development/CommandViewer/issues/9

**Comment by Wild1145** [comment]
@Zilacon Sorry for not getting back to you, I only just saw this issue. I will investigate the issue, it may well be an issue with one of the other in-built dependencies.

**Comment by Wild1145** [comment]
It looks like its running on a Forge server here, not Bukkit. This could well be the issue at hand.

**Comment by Zilacon** [comment]
MCPC+ is a forge server but it uses the Bukkit API. I have no issues running over 65 other bukkit plugins.

**Comment by Wild1145** [comment]
@Zilacon Hmmm, I havent tested it on MCPC+ but I will do some tests and see if I can figure out exactly why the plugin is not working as it should be.

**Comment by Wild1145** [comment]
Thinking about it some more, with the release of 1.9 I dont think there is the scope to be trying to support 1.6.X anymore, and we will be ending support for 1.7.X in the next few releases.
